#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "6647579804:AAEv9Ps4qcPMcpXTg-bZQGaHG_-j6GRUxi4")
    API_ID = int(os.environ["API_ID", 21617866]
    API_HASH = os.environ["API_HASH", "fae6ca0bec0ddfce29fa6d75d7c61c90"]
    AUTH_USERS = "6959409818"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
